# Placeholders
VALUE = "<value>"
CONDITION = "<condition>"
EXPRESSION = "<expression>"
START_VALUE = "<start-value>"
END_VALUE = "<end-value>"
STEP_VALUE = "<step-value>"
VARIABLE = "<variable>"
VALUE_EXPRESSION = "<value> or <expression>"
VALUE_OF = "<value-of-type-{}>"

# Templates
VAR_NAME_EXAMPLE = "variable_name"
FUNC_NAME_EXAMPLE = "FunctionName"
VAR_FUNC_NAME_EXAMPLE = "varFuncName"

# Error messages
OUT_OF_BOUNDS_ERROR = "Out of bounds"
DIVISION_BY_ZERO_ERROR = "Division by zero"
ILLEGAL_OPERATION_ERROR = "Illegal operation"
CANNOT_OVERWRITE_IMMUTABLE_VAR_ERROR = "Cannot overwrite the immutable variable '{}'"
CANNOT_OVERWRITE_BUILTIN_FUNC_ERROR = "Cannot overwrite the builtin function '{}'"
IS_NOT_DEFINED_ERROR = "'{}' Is not defined"
WAS_NOT_INITIALIZED_ERROR = "'{}' Is not initialized"
NO_METHOD_DEFINED_ERROR = "No '{}' method defined"
VAR_ALREADY_INITIALIZED_ERROR = "Variable '{}' is already initialized"
VAR_TYPE_DECLARED_BUT_VALUE_TYPE_IS_NOT_SAME_ERROR = "Variable '{}' was declared as a '{}', but the value type is different"
VAR_TYPE_ALREADY_DECLARED_CANNOT_CHANGE_ERROR = "Cannot change variable '{}' value type once initialized"
VAR_TYPE_INVALID_ERROR = "Variable '{}' was declared, but with a invalid type"
UNKNOWN_FAIL_TYPE_ERROR = "Unknown Fail Type"
CANNOT_DECLARE_TYPE_AFTER_DECLARED_ERROR = "Cannot declare another value type after the variable have been initialized"